### ISSUE TITLE
 The sandbox is not in sync with the Podfile.lock.

### ISSUE THREAD

**Issue by codeoholic** [blockstack/blockstack-react-native#21]
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening example-sdk-module.xcworkspace

**Comment by shreyasthiagaraj** [comment]
Hey, please do `npm update` and try again. Just pushed some fixes to the repo :).

**Comment by devdotmohit** [comment]
@shreyasthiagaraj Still the same.

Check dependencies
The file “Pods-example-sdk-module.debug.xcconfig” couldn’t be opened because there is no such file. (/Volumes/Development/react-native/blockstack-react-native/example/ios/Pods/Pods/Target Support Files/Pods-example-sdk-module/Pods-example-sdk-module.debug.xcconfig)

I see wrong directory here, Pods repeated twice.

**Comment by shreyasthiagaraj** [comment]
Can you try this:

1. Delete the `Pods` folder
2. Delete `Podfile.lock`
3. Run `pod install` 
4. Clean + Build

I feel like it may be an issue with your environment since it is not happening on my end.

**Comment by shreyasthiagaraj** [comment]
Closing as I believe this is fixed. Please reopen if you still run into this :).

**Comment by cs-manughian** [comment]
For me, cleaning, clearing the Derived Data, and pod installing did the trick! (I used DevCleaner to clear the Derived Data)
